# Generated by Django 3.1.6 on 2021-06-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=120)),
                ('name', models.CharField(default='', max_length=120)),
                ('amount_of_rooms', models.IntegerField(default=0)),
                ('amount_of_beds', models.IntegerField(default=0)),
                ('occupated_beds', models.IntegerField(default=0)),
                ('about', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('amount_of_beds', models.IntegerField(default=0)),
                ('hostel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=30)),
                ('telephone_number', models.CharField(blank=True, max_length=15)),
                ('passport_photo', models.TextField(default='')),
                ('fee', models.FloatField(default=0)),
                ('payment_day', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('moving_in_date', models.DateField()),
                ('bed_number', models.IntegerField()),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
