# Generated by Django 3.1.6 on 2021-03-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=30)),
                ('passport_photo', models.ImageField(upload_to='')),
                ('fee', models.FloatField()),
                ('payment_day', models.DateField()),
                ('is_paid', models.BooleanField()),
                ('moving_in_date', models.DateField()),
                ('bed_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('amount_of_beds', models.IntegerField()),
                ('occupated_beds', models.IntegerField()),
                ('tenants', models.ManyToManyField(to='api.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('adress', models.TextField()),
                ('amount_of_rooms', models.IntegerField()),
                ('amount_of_beds', models.IntegerField()),
                ('free_beds', models.IntegerField()),
                ('about', models.TextField()),
                ('Gallery', models.ManyToManyField(to='api.Gallery')),
                ('rooms', models.ManyToManyField(to='api.Room')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=models.ManyToManyField(to='api.Picture'),
        ),
    ]
