# Generated by Django 3.1.6 on 2021-06-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='passport_number',
        ),
    ]
