# Generated by Django 3.1.6 on 2021-06-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tenant_passport_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='payment_day',
            new_name='next_payment_date',
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
