# Generated by Django 3.1.6 on 2021-06-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210613_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
